package com.backend_project.backend_hobby_project.enums;

public enum DaysOfTheWeek {
    MONDAYMORNING,
    MONDAYAFTERNOON,
    MONDAYEVENING,
    TUESDAYMORNING,
    TUESDAYAFTERNOON,
    TUESDAYEVENING,
    WEDNESDAYMORNING,
    WEDNESDAYAFTERNOON,
    WEDNESDAYEVENING,
    THURSDAYMORNING,
    THURSDAYAFTERNOON,
    THURSDAYEVENING,
    FRIDAYMORNING,
    FRIDAYAFTERNOON,
    FRIDAYEVENING,
    SATURDAYMORNING,
    SATURDAYAFTERNOON,
    SATURDAYEVENING,
    SUNDAYMORNING,
    SUNDAYAFTERNOON,
    SUNDAYEVENING
}